---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-rpm-centos8
    image: rancher/dapper:v0.5.2
    commands:
    - dapper scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - tag
  - name: sign-rpm-centos8
    image: centos:7
    environment:
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      RPMARCH: x86_64
    commands:
    - scripts/sign
    when:
      event:
      - tag
  - name: yum-repo-upload-centos8
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: testing_aws_session_token
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
      TESTING_AWS_SESSION_TOKEN:
        from_secret: testing_aws_session_token
      RPMARCH: x86_64
    commands:
    - scripts/upload-repo
    when:
      event:
      - tag
  - name: github-release-centos8-rpm
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-rpm.txt
      checksum_flatten: true
      files:
      - "containerd-packaging/build/centos/8/x86_64/*.rpm"
    when:
      event:
      - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
